version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./dist:/usr/src/app/dist
    environment:
      - NODE_ENV=production