# Workflow name
name: Deploy Static Frontend to GitHub Pages

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:

permissions:
  contents: write 

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x 
          cache: 'npm' 

      - name: Install Dependencies
        run: npm ci 

      - name: Build Project
        run: npm run build

      # --- NEW: Verify Build Output ---
      - name: List Build Artifacts
        run: |
          echo "--- Listing dist/ ---"
          ls -R dist || echo "dist/ directory not found."
          echo "--- Listing styles/ ---"
          ls -R styles || echo "styles/ directory not found."
          echo "--- Listing public/ ---"
          ls -R public || echo "public/ directory not found."
          echo "--- Listing data/ ---"
          ls -R data || echo "data/ directory not found."
      # --- End Verification Step ---

      # Step 5: Prepare deployment directory ('docs' folder)
      - name: Prepare Deployment Directory
        run: |
          mkdir -p docs 
          echo "Copying files to docs/ ..."
          # Check if source HTML files exist before copying
          ls public/*.html && cp public/index.html public/admin.html public/post.html docs/ || echo "HTML files not found in public/, skipping."
          # Copy directories recursively, handle errors if source doesn't exist
          cp -r public/images docs/images || echo "No public/images directory found, skipping."
          cp -r public/fonts docs/fonts || echo "No public/fonts directory found, skipping."
          cp -r styles docs/styles || echo "No styles directory found, skipping."
          
          mkdir -p docs/dist 
          cp -r dist/client docs/dist/client || echo "No dist/client directory found, skipping."
          
          # Optional: Copy data if needed client-side
          cp data/posts.json docs/data/posts.json || echo "No data/posts.json found, skipping."
          echo "Finished copying files."
          echo "--- Listing final docs/ contents ---" # Added header for clarity
          ls -R docs 

      # Step 6: Fix paths in HTML files within 'docs' directory
      - name: Fix HTML Paths
        run: |
          echo "Fixing paths in HTML files..."
          find docs/ -name '*.html' -print0 | xargs -0 sed -i 's|href="/|href="|g'
          find docs/ -name '*.html' -print0 | xargs -0 sed -i 's|src="/|src="|g'
          echo "HTML paths fixed."
      
      # Step 7: Fix paths in CSS files within 'docs' directory (Basic Example)
      - name: Fix CSS Paths (Basic)
        run: |
          echo "Fixing basic paths in CSS files..."
          find docs/styles/ -name '*.css' -print0 | xargs -0 sed -i 's|url(/|url(../|g' 
          echo "Basic CSS paths adjusted."

      # Step 8: Deploy the 'docs' folder to the 'gh-pages' branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 
